#!/usr/bin/env python3
# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""ZTAB CLI — Agent Broker client for Echo and Session RPCs.

Usage:
    # First, generate proto stubs (one-time):
    python3 generate_protos.py

    # Echo (backward compatible):
    python3 cli.py echo --message "hello from agent"

    # Session workflow (two terminals):
    # Terminal 1 (creator):
    python3 cli.py create-session --policy ExtractAndResolve --participants 2
    python3 cli.py get-status --session-id <SID>
    python3 cli.py submit-input --session-id <SID> --token <TOK> --input '{"available_slots":["2026-07-01T10:00:00Z"]}'
    python3 cli.py get-result --session-id <SID> --token <TOK>

    # Terminal 2 (joiner):
    python3 cli.py join-session --session-id <SID>
    python3 cli.py accept-policy --session-id <SID> --token <TOK>
    python3 cli.py submit-input --session-id <SID> --token <TOK> --input '{"available_slots":["2026-07-01T10:00:00Z","2026-07-01T14:00:00Z"]}'
    python3 cli.py get-result --session-id <SID> --token <TOK>
"""

import argparse
import json
import logging
import sys
import os
from os.path import abspath, dirname, join

# Add the agent directory and pb2 directory to the path to import library and stubs.
sys.path.insert(0, dirname(abspath(__file__)))
sys.path.insert(0, join(dirname(abspath(__file__)), "pb2"))

import grpc
from client import ZtabChannel
from verifier_factory import get_verifier as _get_verifier

# These are generated by generate_protos.py inside pb2/ directory.
import session_manager_pb2
import session_manager_pb2_grpc


def _make_stub(args):
    """Create a connected gRPC stub from common connection args."""
    verifier = _get_verifier(
        args.verifier,
        getattr(args, 'expected_digest', None),
        allow_debug=getattr(args, 'allow_debug_tee', False),
    )
    channel_wrapper = ZtabChannel(host=args.host, port=args.port, verifier=verifier)
    channel_wrapper.connect()
    stub = session_manager_pb2_grpc.AgentBrokerServiceStub(channel_wrapper.grpc_channel)
    return stub, channel_wrapper


def _add_connection_args(parser):
    """Add common connection arguments to a subparser."""
    parser.add_argument("--host", default="localhost", help="Server host (default: localhost)")
    parser.add_argument("--port", type=int, default=8000, help="Server port (default: 8000)")
    parser.add_argument(
        "--verifier", required=True, choices=["noop", "ita"],
        help="Attestation verifier to use (e.g., 'noop' or 'ita')",
    )
    parser.add_argument("--expected-digest", default=None, help="Expected container image digest")
    parser.add_argument("--allow-debug-tee", action="store_true", default=False)
    parser.add_argument("-q", "--quiet", action="store_true", help="Suppress attestation details")


def cmd_echo(args):
    """Original Echo RPC for backward compatibility and health checks."""
    stub, channel = _make_stub(args)
    try:
        request = session_manager_pb2.EchoRequest(message=args.message)
        print(f"Sending Echo request: '{args.message}'")
        response = stub.Echo(request)
        print(f"Echo response: '{response.message}'")
        print("\nEnd-to-end TLS + gRPC test PASSED.")
    finally:
        channel.close()


def cmd_create_session(args):
    """Create a new multi-agent session."""
    stub, channel = _make_stub(args)
    try:
        policy = session_manager_pb2.SessionPolicy(
            policy_class=args.policy,
            expected_participants=args.participants,
            timeout_seconds=args.timeout,
        )
        if args.input_schema:
            policy.input_schema_json = args.input_schema
        if args.output_schema:
            policy.output_schema_json = args.output_schema

        request = session_manager_pb2.CreateSessionRequest(policy=policy)
        response = stub.CreateSession(request)

        print(f"Session created successfully.")
        print(f"  session_id: {response.session_id}")
        print(f"  state:      {session_manager_pb2.SessionState.Name(response.state)}")
        print(f"  token:      {response.participant_token}")
        print(f"\nShare the session_id with other participants.")
        print(f"Your token is secret — use it for subsequent RPCs.")
    finally:
        channel.close()


def cmd_join_session(args):
    """Join an existing session."""
    stub, channel = _make_stub(args)
    try:
        request = session_manager_pb2.JoinSessionRequest(
            session_id=args.session_id,
            role=args.role or "",
        )
        response = stub.JoinSession(request)

        print(f"Joined session successfully.")
        print(f"  state:        {session_manager_pb2.SessionState.Name(response.state)}")
        print(f"  policy_class: {response.policy.policy_class}")
        print(f"  expected:     {response.policy.expected_participants} participants")
        print(f"  token:        {response.participant_token}")
        print(f"\nReview the policy above, then call accept-policy.")
    finally:
        channel.close()


def cmd_accept_policy(args):
    """Accept the session policy (must be called before submitting input)."""
    stub, channel = _make_stub(args)
    try:
        request = session_manager_pb2.AcceptPolicyRequest(
            session_id=args.session_id,
            participant_token=args.token,
        )
        response = stub.AcceptPolicy(request)

        state_name = session_manager_pb2.SessionState.Name(response.state)
        print(f"Policy accepted.")
        print(f"  state: {state_name}")
        if response.state == session_manager_pb2.SEALED:
            print(f"\nAll participants have accepted. Session is SEALED.")
            print(f"You can now submit your input.")
        else:
            print(f"\nWaiting for other participants to accept.")
    finally:
        channel.close()


def cmd_submit_input(args):
    """Submit private input to the session."""
    stub, channel = _make_stub(args)
    try:
        # Read input from --input flag or stdin.
        input_json = args.input
        if input_json == "-":
            input_json = sys.stdin.read()

        # Validate it's valid JSON.
        try:
            json.loads(input_json)
        except json.JSONDecodeError as e:
            print(f"Error: Invalid JSON input: {e}", file=sys.stderr)
            sys.exit(1)

        request = session_manager_pb2.SubmitInputRequest(
            session_id=args.session_id,
            participant_token=args.token,
            input_json=input_json,
        )
        response = stub.SubmitInput(request)

        state_name = session_manager_pb2.SessionState.Name(response.state)
        print(f"Input submitted.")
        print(f"  state:     {state_name}")
        print(f"  remaining: {response.remaining_inputs} inputs needed")
        if response.remaining_inputs == 0:
            print(f"\nAll inputs received. LLM processing has started.")
            print(f"Call get-result to retrieve the output.")
        else:
            print(f"\nWaiting for {response.remaining_inputs} more input(s).")
    finally:
        channel.close()


def cmd_get_result(args):
    """Get the session result."""
    stub, channel = _make_stub(args)
    try:
        request = session_manager_pb2.GetResultRequest(
            session_id=args.session_id,
            participant_token=args.token,
        )
        response = stub.GetResult(request)

        state_name = session_manager_pb2.SessionState.Name(response.state)
        print(f"  state: {state_name}")

        if response.state == session_manager_pb2.CLOSED:
            print(f"\nResult:")
            # Pretty-print if valid JSON.
            try:
                result = json.loads(response.result_json)
                print(json.dumps(result, indent=2))
            except json.JSONDecodeError:
                print(response.result_json)
        elif response.state == session_manager_pb2.ABORTED:
            error_name = session_manager_pb2.SessionError.Name(response.error_code)
            print(f"\nSession ABORTED:")
            print(f"  error: {error_name}")
            print(f"  detail: {response.error_detail}")
        else:
            print(f"\nResult not yet available. Session is still {state_name}.")
            print(f"Try again after all inputs are submitted.")
    finally:
        channel.close()


def cmd_get_status(args):
    """Get current session status."""
    stub, channel = _make_stub(args)
    try:
        request = session_manager_pb2.GetSessionStatusRequest(
            session_id=args.session_id,
            participant_token=args.token,
        )
        response = stub.GetSessionStatus(request)

        state_name = session_manager_pb2.SessionState.Name(response.state)
        print(f"Session status:")
        print(f"  state:    {state_name}")
        print(f"  joined:   {response.participants_joined}")
        print(f"  accepted: {response.participants_accepted}")
        print(f"  inputs:   {response.inputs_received}")
    finally:
        channel.close()


def main():
    parser = argparse.ArgumentParser(
        description="ZTAB CLI — Agent Broker client for Echo and Session RPCs.",
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # --- echo ---
    echo_parser = subparsers.add_parser("echo", help="Send an Echo RPC (health check)")
    _add_connection_args(echo_parser)
    echo_parser.add_argument("--message", default="hello from ZTAB client", help="Message to send")

    # --- create-session ---
    create_parser = subparsers.add_parser("create-session", help="Create a new multi-agent session")
    _add_connection_args(create_parser)
    create_parser.add_argument("--policy", default="ExtractAndResolve", help="Policy class name")
    create_parser.add_argument("--participants", type=int, default=2, help="Expected participant count")
    create_parser.add_argument("--timeout", type=int, default=300, help="Per-state timeout in seconds")
    create_parser.add_argument("--input-schema", default="", help="JSON Schema for input validation (optional)")
    create_parser.add_argument("--output-schema", default="", help="JSON Schema for output validation (optional)")

    # --- join-session ---
    join_parser = subparsers.add_parser("join-session", help="Join an existing session")
    _add_connection_args(join_parser)
    join_parser.add_argument("--session-id", required=True, help="Session ID to join")
    join_parser.add_argument("--role", default="", help="Role for role-based policies (Phase 2+)")

    # --- accept-policy ---
    accept_parser = subparsers.add_parser("accept-policy", help="Accept the session policy")
    _add_connection_args(accept_parser)
    accept_parser.add_argument("--session-id", required=True, help="Session ID")
    accept_parser.add_argument("--token", default=os.environ.get("ZTAB_TOKEN"), help="Your participant token (or set ZTAB_TOKEN)")

    # --- submit-input ---
    submit_parser = subparsers.add_parser("submit-input", help="Submit private input to the session")
    _add_connection_args(submit_parser)
    submit_parser.add_argument("--session-id", required=True, help="Session ID")
    submit_parser.add_argument("--token", default=os.environ.get("ZTAB_TOKEN"), help="Your participant token (or set ZTAB_TOKEN)")
    submit_parser.add_argument(
        "--input", required=True,
        help="JSON input string, or '-' to read from stdin",
    )

    # --- get-result ---
    result_parser = subparsers.add_parser("get-result", help="Get the session result")
    _add_connection_args(result_parser)
    result_parser.add_argument("--session-id", required=True, help="Session ID")
    result_parser.add_argument("--token", default=os.environ.get("ZTAB_TOKEN"), help="Your participant token (or set ZTAB_TOKEN)")

    # --- get-status ---
    status_parser = subparsers.add_parser("get-status", help="Get current session status")
    _add_connection_args(status_parser)
    status_parser.add_argument("--session-id", required=True, help="Session ID")
    status_parser.add_argument("--token", default=os.environ.get("ZTAB_TOKEN"), help="Your participant token (or set ZTAB_TOKEN)")

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        sys.exit(1)

    if hasattr(args, "token") and not args.token:
        print("Error: The --token flag or ZTAB_TOKEN environment variable is required for this command.", file=sys.stderr)
        sys.exit(1)

    # Configure logging.
    log_level = logging.WARNING if getattr(args, 'quiet', False) else logging.INFO
    logging.basicConfig(level=log_level, format="%(message)s", stream=sys.stderr)

    try:
        commands = {
            "echo": cmd_echo,
            "create-session": cmd_create_session,
            "join-session": cmd_join_session,
            "accept-policy": cmd_accept_policy,
            "submit-input": cmd_submit_input,
            "get-result": cmd_get_result,
            "get-status": cmd_get_status,
        }
        commands[args.command](args)

    except grpc.RpcError as e:
        print(f"\ngRPC error: {e.code()}: {e.details()}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"\nError: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
