#!/usr/bin/env python3
# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""ZTAB CLI Tester.

Connects to a ZTAB server, verifies attestation (no-op), calls Echo, and
prints the result.

Usage:
    # First, generate proto stubs (one-time):
    python3 generate_protos.py

    # Then run:
    python3 cli.py --host localhost --port 8000 --message "hello from agent"
"""

import argparse
import sys
import os

# Add the agent directory and pb2 directory to the path to import library and stubs.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "pb2"))

import grpc
from client import ZtabChannel, noop_verifier

# These are generated by generate_protos.py inside pb2/ directory.
import session_manager_pb2
import session_manager_pb2_grpc


def main():
    parser = argparse.ArgumentParser(
        description="ZTAB CLI Tester: connect, verify attestation, call Echo."
    )
    parser.add_argument(
        "--host", default="localhost", help="Server host (default: localhost)"
    )
    parser.add_argument(
        "--port", type=int, default=8000, help="Server port (default: 8000)"
    )
    parser.add_argument(
        "--message",
        default="hello from ZTAB client",
        help="Message to send via Echo RPC",
    )
    args = parser.parse_args()

    try:
        with ZtabChannel(host=args.host, port=args.port, verifier=noop_verifier) as channel:
            # Create a stub and call Echo.
            stub = session_manager_pb2_grpc.AgentBrokerServiceStub(channel.grpc_channel)
            request = session_manager_pb2.EchoRequest(message=args.message)

            print(f"\nSending Echo request: '{args.message}'")
            response = stub.Echo(request)
            print(f"Echo response: '{response.message}'")
            print("\nEnd-to-end TLS + gRPC test PASSED.")

    except grpc.RpcError as e:
        print(f"\ngRPC error: {e.code()}: {e.details()}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"\nError: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
